// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsySchedule.Context;

#nullable disable

namespace PsySchedule.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260827081652_AddColumnGap")]
    partial class AddColumnGap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PsySchedule.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientConfirmation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PsychologistConfirmation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Created");

                    b.Property<int>("WorkDayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("WorkDayId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("PsySchedule.Models.AppointmentНistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewState")
                        .HasColumnType("integer");

                    b.Property<int>("OldState")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentНistory");
                });

            modelBuilder.Entity("PsySchedule.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramName")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("PsySchedule.Models.Psychologist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ScheduleTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("ScheduleTemplateId")
                        .IsUnique();

                    b.ToTable("Psychologist");
                });

            modelBuilder.Entity("PsySchedule.Models.ScheduleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BreakFinishedAt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("BreakStartedAt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("FinishedAt")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Gap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Weekend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("ScheduleTemplate");
                });

            modelBuilder.Entity("PsySchedule.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("PsySchedule.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenAccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenRefresh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TokenRefresh");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("PsySchedule.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FinishedAt")
                        .HasColumnType("date");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Vacation");
                });

            modelBuilder.Entity("PsySchedule.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BreakFinishedAt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("BreakStartedAt")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("FinishedAt")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Gap")
                        .HasColumnType("integer");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleTemplateId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartedAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Generated");

                    b.Property<int>("Weekend")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("ScheduleTemplateId");

                    b.ToTable("WorkDay");
                });

            modelBuilder.Entity("PsySchedule.Models.Appointment", b =>
                {
                    b.HasOne("PsySchedule.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsySchedule.Models.Psychologist", "Psychologist")
                        .WithMany("Appointments")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsySchedule.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsySchedule.Models.WorkDay", "WorkDay")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Psychologist");

                    b.Navigation("Service");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("PsySchedule.Models.AppointmentНistory", b =>
                {
                    b.HasOne("PsySchedule.Models.Appointment", "Appointment")
                        .WithMany("AppointmentНistories")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PsySchedule.Models.Psychologist", b =>
                {
                    b.HasOne("PsySchedule.Models.ScheduleTemplate", "ScheduleTemplate")
                        .WithOne("Psychologist")
                        .HasForeignKey("PsySchedule.Models.Psychologist", "ScheduleTemplateId");

                    b.Navigation("ScheduleTemplate");
                });

            modelBuilder.Entity("PsySchedule.Models.Service", b =>
                {
                    b.HasOne("PsySchedule.Models.Psychologist", "Psychologist")
                        .WithMany("Services")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PsySchedule.Models.Token", b =>
                {
                    b.HasOne("PsySchedule.Models.Psychologist", "Psychologist")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PsySchedule.Models.Vacation", b =>
                {
                    b.HasOne("PsySchedule.Models.Psychologist", "Psychologist")
                        .WithMany("Vacations")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PsySchedule.Models.WorkDay", b =>
                {
                    b.HasOne("PsySchedule.Models.Psychologist", "Psychologist")
                        .WithMany("WorkDays")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsySchedule.Models.ScheduleTemplate", "ScheduleTemplate")
                        .WithMany()
                        .HasForeignKey("ScheduleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("ScheduleTemplate");
                });

            modelBuilder.Entity("PsySchedule.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentНistories");
                });

            modelBuilder.Entity("PsySchedule.Models.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PsySchedule.Models.Psychologist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Services");

                    b.Navigation("Vacations");

                    b.Navigation("WorkDays");
                });

            modelBuilder.Entity("PsySchedule.Models.ScheduleTemplate", b =>
                {
                    b.Navigation("Psychologist")
                        .IsRequired();
                });

            modelBuilder.Entity("PsySchedule.Models.WorkDay", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
